# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb90e2efddfaffb3ec1cce1496eda244c536d7bdf75e7f8c49cd28eedcb714939fb165a9820552b0a722df6cfb6e35f2c5db92f0bd0d38d141ac40bbb7eafda5

test:
  secret_key_base: 57068c48cdc25d38bd13c38fdc9bedb3da78632e9185c42972c76055a6fb37af61595060f7312458f55fc703c129b0b5fbb81b64f9b29c986c90739fd1ae22b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
